"""Cellpose-SAM as a first-class PiMorph proposer.

Cellpose (>= 4) is the strongest general segmenter we have measured, and on the cultured
endothelial monolayer a Cellpose-SAM fine-tuned on ten fields out-scores PiMorph's own
proposal network on adjacency and PQ. This module turns its output into ``ProposalMaps``
so that the constrained decoder, the energy and the posterior ensemble run on top of it:
the masks become a valid complex by construction, and the hypothesis family is generated by
perturbing Cellpose's own decision thresholds (flow error, cell probability) from a single
network pass, plus the decoder's usual perturbations and moves.

Optional dependency: ``cellpose`` and ``torch`` are imported lazily. ``maps_from_masks`` has
no such dependency and works for any label image.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, List, Optional, Sequence, Tuple

import numpy as np
from scipy import ndimage as ndi
from skimage.segmentation import find_boundaries

from .cellpose_sam import pick_device
from .decoder import ConstrainedDecoder, DecoderParams
from .proposals import ProposalMaps, estimate_nucleus_radius


def _sigmoid(x: np.ndarray) -> np.ndarray:
    return (1.0 / (1.0 + np.exp(-np.clip(x, -30.0, 30.0)))).astype(np.float32)


def fill_thin_seams(labels: np.ndarray, half_width_px: float = 1.5) -> np.ndarray:
    """Assign background pixels that lie in a thin seam BETWEEN two cells to the nearest
    cell. A background pixel is a seam pixel when it is within ``half_width_px`` of a cell
    and its 3x3 neighbourhood of nearest-cell labels holds at least two different cells;
    background that borders a single cell (the tissue edge, a real gap) is left alone.
    Unlike the component-size rule this also fills seam networks that connect to the
    exterior, which Cellpose masks produce along whole rows of cells."""
    lab = np.asarray(labels).astype(np.int32)
    fg = lab > 0
    if not fg.any() or fg.all():
        return lab
    dist, idx = ndi.distance_transform_edt(~fg, return_indices=True)
    nearest = lab[idx[0], idx[1]]
    near = (~fg) & (dist <= half_width_px)
    if not near.any():
        return lab
    # number of distinct nearest labels in the 3x3 window: max - min > 0 is a cheap proxy
    # for "at least two", exact because the window is compared against its own values
    mx = ndi.maximum_filter(nearest, size=3)
    mn = ndi.minimum_filter(nearest, size=3)
    seam = near & (mx != mn)
    out = lab.copy()
    out[seam] = nearest[seam]
    return out


def fill_seams(labels: np.ndarray, max_area_px: int = 12, half_width_px: float = 1.5) -> np.ndarray:
    """Thin seams between cells (geometric rule) plus sub-``max_area_px`` enclosed
    background components (the size rule the benchmark applies to polygon truth and to
    Cellpose masks), so touching cells share a crack edge."""
    from .decoder import _fill_small_background

    out = fill_thin_seams(np.asarray(labels).astype(np.int32), half_width_px)
    return _fill_small_background(out, max_area_px)


def signed_distance(labels: np.ndarray) -> np.ndarray:
    """Positive inside cells (distance to the cell's own boundary), negative in background
    (distance to the nearest cell), 0.5 on the inner boundary ring, matching the training
    target of the neural proposer so ``DecoderParams.outside_px`` means the same thing."""
    lab = np.asarray(labels)
    fg = lab > 0
    inner = find_boundaries(lab, mode="inner")
    d_in = ndi.distance_transform_edt(~inner).astype(np.float32) + 0.5
    d_out = ndi.distance_transform_edt(~fg).astype(np.float32)
    return np.where(fg, d_in, -d_out).astype(np.float32)


def tricellular_points(labels: np.ndarray) -> np.ndarray:
    """(N, 2) crack corners where at least three distinct cell labels meet in a 2x2 window."""
    lab = np.asarray(labels)
    a, b, c, d = lab[:-1, :-1], lab[:-1, 1:], lab[1:, :-1], lab[1:, 1:]
    stack = np.stack([a, b, c, d], axis=0)
    srt = np.sort(stack, axis=0)
    distinct = np.ones(a.shape, dtype=np.int32)
    for k in range(1, 4):
        distinct += (srt[k] != srt[k - 1]).astype(np.int32)
    n_cells = distinct - (srt[0] == 0).astype(np.int32)
    rr, cc = np.nonzero(n_cells >= 3)
    return np.stack([rr + 0.5, cc + 0.5], axis=1) if rr.size else np.zeros((0, 2))


def _heatmap(shape: Tuple[int, int], points: np.ndarray, sigma: float) -> np.ndarray:
    h = np.zeros(shape, dtype=np.float32)
    if len(points):
        pr = np.clip(np.round(points[:, 0]).astype(int), 0, shape[0] - 1)
        pc = np.clip(np.round(points[:, 1]).astype(int), 0, shape[1] - 1)
        h[pr, pc] = 1.0
        h = ndi.gaussian_filter(h, sigma=sigma).astype(np.float32)
        m = float(h.max())
        if m > 0:
            h /= m
    return h


def maps_from_masks(
    masks: np.ndarray,
    cellprob: Optional[np.ndarray] = None,
    nuclei: Optional[np.ndarray] = None,
    seam_px: int = 12,
    boundary_sigma: float = 1.0,
    source: str = "cellpose",
    nucleus_points: Optional[np.ndarray] = None,
) -> ProposalMaps:
    """Proposal maps from an instance label image (and, when available, Cellpose's cell
    probability logits).

    boundary: crack pixels between labels and against background, blurred; seed: one
    peak per mask at its centroid, scored by the mean cell probability inside it;
    distance: signed distance so the decoder excludes what Cellpose called background;
    gap: background probability (1 - sigmoid(cellprob), or 1 - foreground where no logits
    exist); vertex: tricellular crack corners of the masks; tissue: foreground dilated by
    half a cell radius. Decoding these maps with default parameters reproduces the masks
    as a valid complex; the maps exist so the same masks can enter the energy and posterior.
    """
    lab = fill_seams(masks, seam_px)
    H, W = lab.shape
    fg = lab > 0
    counts = np.bincount(lab.ravel())
    areas = counts[1:][counts[1:] > 0]
    cell_radius = float(np.sqrt(np.median(areas) / np.pi)) if areas.size else 15.0

    crack = find_boundaries(lab, mode="thick") & (ndi.binary_dilation(fg, iterations=1))
    boundary = ndi.gaussian_filter(crack.astype(np.float32), sigma=boundary_sigma)
    if boundary.max() > 0:
        boundary = (boundary / boundary.max()).astype(np.float32)

    ids = np.unique(lab[fg])
    if ids.size:
        cents = np.asarray(ndi.center_of_mass(fg, lab, ids), dtype=np.float64)
        # a centroid can fall outside a concave cell; snap it to the nearest own pixel
        for i, lid in enumerate(ids):
            r, c = int(round(cents[i, 0])), int(round(cents[i, 1]))
            r, c = min(max(r, 0), H - 1), min(max(c, 0), W - 1)
            if lab[r, c] != lid:
                rr, cc = np.nonzero(lab == lid)
                k = int(np.argmin((rr - cents[i, 0]) ** 2 + (cc - cents[i, 1]) ** 2))
                cents[i] = (rr[k], cc[k])
        if cellprob is not None:
            # scored on the original mask pixels: filled seams carry low probability by construction
            p = _sigmoid(np.asarray(cellprob, dtype=np.float32))
            orig = np.asarray(masks).astype(np.int32)
            scores = np.asarray(ndi.mean(p, orig, ids), dtype=np.float32)
            scores = np.nan_to_num(scores, nan=0.5)
        else:
            scores = np.ones(ids.size, dtype=np.float32)
        order = np.argsort(-scores, kind="stable")
        cents, scores = cents[order], scores[order]
    else:
        cents, scores = np.zeros((0, 2)), np.zeros(0, dtype=np.float32)
    seed = _heatmap((H, W), cents, sigma=max(0.15 * cell_radius, 1.0))

    if cellprob is not None:
        gap = 1.0 - _sigmoid(np.asarray(cellprob, dtype=np.float32))
    else:
        gap = (~fg).astype(np.float32)
    tissue = ndi.binary_dilation(fg, iterations=max(int(round(cell_radius / 2)), 1))
    if cellprob is not None:
        tissue |= gap < 0.5

    vertex = _heatmap((H, W), tricellular_points(lab), sigma=2.0)
    meta = {
        "cell_radius_px": cell_radius,
        "ridge_width_px": 2.0,
        "n_masks": int(ids.size),
        "nucleus_points": nucleus_points,
    }
    if nuclei is not None:
        meta["nucleus_radius_px"] = estimate_nucleus_radius(np.asarray(nuclei, dtype=np.float32))
    return ProposalMaps(
        boundary=boundary,
        seed=seed,
        tissue=tissue.astype(bool),
        gap=gap.astype(np.float32),
        sigma=np.ones((H, W), dtype=np.float32),
        seed_points=cents.astype(np.float64),
        seed_scores=scores.astype(np.float32),
        vertex=vertex,
        distance=signed_distance(lab),
        source=source,
        meta=meta,
    )


@dataclass
class CellposeRaw:
    """One network pass: masks at the default thresholds plus the flow field and cell
    probability logits from which masks at other thresholds are recomputed."""

    masks: np.ndarray
    dP: np.ndarray  # (2, H, W)
    cellprob: np.ndarray  # (H, W) logits
    diameter: Optional[float]


class CellposeProposer:
    """Cellpose-SAM (or a fine-tuned Cellpose model) as a PiMorph proposer.

    ``__call__`` returns ProposalMaps for the default thresholds; ``raw`` keeps the flow
    field so ``maps_grid`` can produce maps for other flow / cell-probability thresholds
    without running the network again. Nuclei are passed to Cellpose as the second channel
    and, when present, their peaks are exposed to the decoder's nucleus-consistency merges.
    """

    def __init__(
        self,
        pretrained_model: str = "cpsam",
        device=None,
        flow_threshold: float = 0.4,
        cellprob_threshold: float = 0.0,
        diameter: Optional[float] = None,
        seam_px: int = 12,
        nucleus_points: bool = True,
    ):
        from cellpose import models

        self.device = device or pick_device()
        gpu = self.device.type in ("cuda", "mps")
        try:
            self.model = models.CellposeModel(gpu=gpu, pretrained_model=pretrained_model, device=self.device)
        except TypeError:
            self.model = models.CellposeModel(gpu=gpu, pretrained_model=pretrained_model)
        self.pretrained_model = str(pretrained_model)
        self.flow_threshold = float(flow_threshold)
        self.cellprob_threshold = float(cellprob_threshold)
        self.diameter = diameter
        self.seam_px = int(seam_px)
        self.nucleus_points = bool(nucleus_points)

    def raw(self, geometry: np.ndarray, nuclei: Optional[np.ndarray] = None) -> CellposeRaw:
        g = np.asarray(geometry, dtype=np.float32)
        img = np.stack([g, np.asarray(nuclei, dtype=np.float32)], axis=-1) if nuclei is not None else g
        masks, flows, _ = self.model.eval(
            img,
            diameter=self.diameter,
            flow_threshold=self.flow_threshold,
            cellprob_threshold=self.cellprob_threshold,
        )
        dP = np.asarray(flows[1], dtype=np.float32)
        cellprob = np.asarray(flows[2], dtype=np.float32)
        return CellposeRaw(np.asarray(masks).astype(np.int32), dP, cellprob, self.diameter)

    def masks_at(self, raw: CellposeRaw, flow_threshold: float, cellprob_threshold: float) -> np.ndarray:
        """Masks for other thresholds from the stored flows (no network pass)."""
        from cellpose import dynamics

        try:
            out = dynamics.compute_masks(
                raw.dP,
                raw.cellprob,
                flow_threshold=float(flow_threshold),
                cellprob_threshold=float(cellprob_threshold),
                device=self.device,
            )
        except TypeError:
            out = dynamics.compute_masks(
                raw.dP, raw.cellprob, flow_threshold=float(flow_threshold), cellprob_threshold=float(cellprob_threshold)
            )
        masks = out[0] if isinstance(out, (tuple, list)) else out
        return np.asarray(masks).astype(np.int32)

    def _nucleus_points(self, nuclei: Optional[np.ndarray]) -> Optional[np.ndarray]:
        if nuclei is None or not self.nucleus_points:
            return None
        from .neural.proposer import nucleus_peaks

        r = estimate_nucleus_radius(np.asarray(nuclei, dtype=np.float32))
        return nucleus_peaks(nuclei, r) if r is not None else None

    def maps(self, raw: CellposeRaw, masks: Optional[np.ndarray] = None, nuclei=None, tag: str = "") -> ProposalMaps:
        m = raw.masks if masks is None else masks
        return maps_from_masks(
            m,
            cellprob=raw.cellprob,
            nuclei=nuclei,
            seam_px=self.seam_px,
            source=f"cellpose:{self.pretrained_model}{tag}",
            nucleus_points=self._nucleus_points(nuclei),
        )

    def __call__(
        self,
        geometry: np.ndarray,
        nuclei: Optional[np.ndarray] = None,
        junction: Optional[np.ndarray] = None,
        tissue: Optional[np.ndarray] = None,
    ) -> ProposalMaps:
        raw = self.raw(geometry, nuclei)
        maps = self.maps(raw, nuclei=nuclei)
        if tissue is not None:
            maps.tissue = maps.tissue | np.asarray(tissue, dtype=bool)
        return maps

    def maps_grid(
        self,
        raw: CellposeRaw,
        nuclei: Optional[np.ndarray] = None,
        flow_thresholds: Sequence[float] = (0.3, 0.4, 0.6),
        cellprob_thresholds: Sequence[float] = (-1.0, 0.0, 1.0),
    ) -> List[Tuple[str, ProposalMaps]]:
        """Maps for every (flow, cellprob) threshold pair from one network pass; the
        default pair reuses ``raw.masks``."""
        out = []
        for ft in flow_thresholds:
            for ct in cellprob_thresholds:
                tag = f"_ft{ft}_ct{ct}"
                if abs(ft - self.flow_threshold) < 1e-9 and abs(ct - self.cellprob_threshold) < 1e-9:
                    masks = raw.masks
                else:
                    masks = self.masks_at(raw, ft, ct)
                if masks.max() == 0:
                    continue
                out.append((tag, self.maps(raw, masks=masks, nuclei=nuclei, tag=tag)))
        return out


def cellpose_hypotheses(
    proposer: CellposeProposer,
    geometry: np.ndarray,
    nuclei: Optional[np.ndarray],
    decoder: ConstrainedDecoder,
    base: DecoderParams,
    image: Optional[np.ndarray] = None,
    flow_thresholds: Iterable[float] = (0.3, 0.4, 0.6),
    cellprob_thresholds: Iterable[float] = (-1.0, 0.0, 1.0),
    n_merge_moves: int = 4,
    n_split_moves: int = 4,
    max_per_setting: int = 6,
):
    """Hypothesis family with Cellpose as the proposal source: one network pass, masks at
    a grid of Cellpose thresholds, each decoded with a small decoder perturbation grid and
    merge/split moves. Every hypothesis is scored against the maps of the DEFAULT
    thresholds so energies are comparable across settings. Returns (hypotheses, raw,
    default maps)."""
    from .posterior import generate_hypotheses

    raw = proposer.raw(geometry, nuclei)
    ref_maps = proposer.maps(raw, nuclei=nuclei)
    hyps = []
    for tag, maps in proposer.maps_grid(raw, nuclei, tuple(flow_thresholds), tuple(cellprob_thresholds)):
        params = base.with_(cell_radius_px=float(maps.meta.get("cell_radius_px", base.cell_radius_px)), label=tag)
        hs = generate_hypotheses(
            maps,
            decoder,
            params,
            image=image,
            seed_thresholds=(0.35,),
            seed_drop_fracs=(0.0,),
            boundary_smooth_sigmas=(0.0, 1.0),
            distance_mixes=(0.0,),
            n_merge_moves=n_merge_moves,
            n_split_moves=n_split_moves,
            max_hypotheses=max_per_setting,
            energy_maps=ref_maps,
        )
        for h in hs:
            h.tag = f"{tag}|{h.tag}"
        hyps.extend(hs)
    # pixel-identical complexes from different threshold settings count once
    seen = set()
    unique = []
    for h in hyps:
        key = h.labels.tobytes()
        if key in seen:
            continue
        seen.add(key)
        unique.append(h)
    return unique, raw, ref_maps
